language: node_js
node_js: "7"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
script:
  - yarn run lint
  - yarn run test
  - yarn run build
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - node_modules
