language: node_js
node_js: '7'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn
script:
- yarn run lint
- yarn run test
- yarn run build
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: lee.braddock@cru.org
  api_key:
    secure: EFIhkyp/nD4LXKlqzLWT6Am1R8/KueENqCT/VD6slxozjb+kfvspxUhqUbaP8oh8pv+TLmWdvr+nbArjvnB89RrDRBlJYp2PoqL3mWGbP2MzxCmJ3kFXUvVAvuIhS9g6MJjSw+baTsF64p36ClTpzD526FBmvZDav0TJcvKdFMpSLN1Ms+LZngRbvXfNolLZxL/jRrI4fSovsWoHs1oiXlSSEs6UNaaC2MxHn/+3r+0kfRg58Oqoud481uwUVRcU7CFKXuettHFLdEajLYV92vWEqaeW2mjnVgFA9fV+vtHMUCcAOUvTw93aa097qZSK0xzdJaaDSLb3gDHm034AcT6ODAHGCaOng1EeFRpPwZlRGd2gUG++c/n7P5/oZnhNnfNS1fZ6O55Lz/FLVR5bVkAcBNsfNHjlwEUiS1xYjhb2B8KDO9DXUBjRqmrth4EUpC79gee/nMH48ROuw5sk8dOnFehVHqwD8tIwaSmNRumm4D7UIRDdEvkPi8mqQm4KSI8AEsvs9vWCwZOmnzZE1S52RH5iZmSdBbE1of5icTpvPW0BiLI/tNaGI8zERqdsMM/IvK8FXyFkjolgvaRJoLViCZQDknGZYZFW74UUQ7QWH68l5V1lHXlKPvgP1j/ufGS68cyRLgYR+zHZsRTDuWdpI3lbnSoiIX71qXg8NOw=
  on:
    repo: CruPCI/cru-payments
    branch: master
    tags: true
  skip_cleanup: true
